#!/usr/bin/env python3
import pBandsTools as pbt
import pBandsQuestions as pbq
import TerminalTools as tt
import sys



# print a title of program

tt.ProgramTitle('pBandsMake', 'Nathanael N. Batista', 'nnardoto@gmail.com')

# load input file from argv list without verification
if len(sys.argv) < 2:
	tt.box(">>> ERROR: fisrt argument must be a SETUP file", align = 'left', top = False)
	exit()


# load setup file from project 	
setup = pbt.loadSetup(sys.argv[1])

# states of files in setup
states = pbt.read_states(setup)

# make panora of project
pbt.panorama(states)

# select combination of states to projections calculations
states = pbt.FilterRoutines(states)

tt.box("Your Selections")
for itens in states:
    print(itens + ': ' + ' '.join(states[itens]["state"].to_list()))

pbt.MakeProjBandInput(setup, states, 0.0)