#!/usr/bin/env python3
import pBandsTools as pbt
import pBandsQuestions as pbq
import TerminalTools as tt
import os
import sys
import string
import random



# print a title of program

tt.ProgramTitle('pBandsMake', 'Nathanael N. Batista', 'nnardoto@gmail.com')

# load input file from argv list without verification
if len(sys.argv) < 2:
	tt.box(">>> ERROR: fisrt argument must be a SETUP file", align = 'left', top = False)
	exit()


# load setup file from project 	
setup = pbt.loadSetup(sys.argv[1])

# states of files in setup
states = pbt.read_states(setup)

# make panora of project
pbt.panorama(states)

# select combination of states to projections calculations
states = pbt.FilterRoutines(states)

tt.box("Your Selections")
for itens in states:
    print(itens + ': ' + ' '.join(states[itens]["state"].to_list()))

### Gera um Nome de Projeto Unico para o default ###

# Entra no Diretorio WORK e gera um nome aleatório unico
RandomName = ''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(6))

# Verifica se o nome gerado já existe
while (os.path.exists(setup["work_path"] + RandomName)):
	RandomName = ''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(6))

# Soclicita um Nome de Projeto
tt.box("Project Name")
prefix = input("[default: {}] --> ". format(RandomName)) or RandomName

# Gera os Arquivos .in para o plotbands.x
pbt.MakeProjBandInput(prefix, setup, states, 0.0)

# Roda o plotbands.x para cada arquivo gerado
pbt.RunPlotBandsX(prefix, setup, states)

# Gera os graficos usando o gnuplot
pbt.MakeGraphics_gnuplot(prefix, setup, states, 0.0)